name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
              cv.tex
              cv_russian.tex
      - name: Push LaTeX documents
        run: |
            git add cv.pdf cv_russian.pdf
            git commit -m "Update PDFs"
            git push


