name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
              cv.tex
      - name: Configure git
        run: |
            git config --global user.email "shadenis2015@gmail.com"
            git config --global user.name "Denis Shabanov"
      - name: Push LaTeX documents
        run: |
            git add cv.pdf
            git commit -m "Update PDFs"
            git push


